# source: https://github.com/ros2/teleop_twist_joy/blob/rolling/README.md
joy_node:
    ros__parameters:
        device_id: 0
        deadzone: 0.3
        autorepeat_rate: 20.0
        sticky_buttons: false

teleop_twist_joy:
    ros__parameters:
        # publish_stamped_twist: true
        axis_linear:                  # Left thumb stick vertical
          x: 1
        scale_linear:
          x: 1.0
        scale_linear_turbo:
          x: 1.5

        axis_angular:                 
          yaw: 3                     # Left thumb stick horizontal
        scale_angular:
          yaw: 1.5
        scale_angular_turbo:
          yaw: 2.0
        
        require_enable_button: true
        enable_button: 4              # Left shoulder button. 
        enable_turbo_button: 5        # Right shoulder button