<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">



    <!-- lidar_link -->
    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="red"/>
            <origin xyz="0.0 0.0 ${lidar_length/2}" rpy="0.0 0.0 0.0"/>          
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${lidar_length/2}" rpy="0.0 0.0 0.0"/>                   
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${lidar_radius}" h="${lidar_length - 0.002}"
                                xyz="0.0 0.0 ${lidar_length/2}" rpy="0.0 0.0 0.0" />             
    </link>



    <!-- body_laser_joint -->
    <joint name="body_laser_joint" type="fixed">
        <parent link="body_link"/>
        <child link="laser"/>
        <origin xyz="0 0 ${body_length - 0.002}" rpy= "0 0 0"/>
    </joint> 





    <gazebo reference="laser">
        <material>Gazebo/Red</material>
    
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                
                <range>
                    <min>0.5</min>
                    <max>12</max>
                    <resolution>0.01</resolution>
                </range>
                
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>

            <!-- <plugin name="laser_sensor" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    Configure namespace and remap to publish to /ray/pointcloud2
                    <argument>~/out:=scan</argument>
                </ros> -->
                <!-- Output as a PointCloud2, see above for other types -->
                <!-- <output_type>sensor_msgs/LaserScan</output_type> -->
                <!-- Clip intensity values so all are above 100, optional -->
                <!-- <min_intensity>100.0</min_intensity> -->
                <!-- Frame id for header of output, defaults to sensor's parent link name -->
                <!-- <frame_name>laser</frame_name>
            </plugin> -->
        </sensor>
    </gazebo>    



</robot>
