<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">



    <xacro:property name="wheel_y_offset" value="0.0775"/>
    <xacro:property name="wheel_z_offset" value="0.0205"/>
    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_length" value="0.025"/>
    <xacro:property name="robot_center_to_base_link_x_distance" value="0.054"/>
    <xacro:property name="robot_center_to_base_link_z_distance" value="0.1375"/>
    <xacro:property name="body_length" value="0.1855"/>
    <xacro:property name="body_radius" value="0.07"/>
    <xacro:property name="caster_wheel_radius" value="0.0125"/>
    <xacro:property name="caster_wheel_length" value="0.013"/>
    <xacro:property name="base_caster_wheel_link_distance" value="0.0485"/>
    <xacro:property name="base_link_inertia_z_offset" value="0.0925"/>
    <xacro:property name="lidar_radius" value="0.0278"/>
    <xacro:property name="lidar_length" value="0.0413"/>
    <xacro:property name="imu_length" value="0.025"/>
    <xacro:property name="imu_width" value="0.02"/>
    <xacro:property name="imu_height" value="0.0015"/>
    <xacro:property name="base_imu_z_distance" value="${body_length - 0.046}"/>

    <xacro:property name= "meshes_file_direction" value="package://my_robot_description/models/meshes"/>

    <!-- base_footprint -->
    <link name="base_footprint" />



    <!-- base_link -->
    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="${meshes_file_direction}/my_robot_base.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="grÃ¼nlichesGrau"/>
            <origin xyz="0.0 0.0 ${robot_center_to_base_link_z_distance}" rpy="${pi/2} 0.0 ${pi/2}"/>          
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${body_radius}" length="${body_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${body_length / 2}" rpy="0.0 0.0 0.0"/>                   
        </collision>
        <xacro:box_inertia m="2.0" l="${body_length}" w="${body_radius * 2}" h="${body_radius * 2}"
                                xyz="0.0 0.0 ${wheel_z_offset + (body_length / 2) - 0.02}" rpy="0.0 0.0 0.0" />             
    </link>



    <!-- footprint_base_joint -->
    <joint name="footprint_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${caster_wheel_radius}" rpy= "0 0 0"/>
    </joint>        



    <!-- wheel_link -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                <mesh filename="${meshes_file_direction}/wheel.stl" scale="0.001 0.001 0.001"/>                    
                </geometry>
                <material name="grauBlau"/>
                <origin xyz="0.0 0.0 ${-wheel_length/2}" rpy="${pi/2}  0.0 0.0"/>         
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>               
            </collision>
            <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_length}"
                                    xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />     
        </link>  
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>



    <!-- base_left_wheel_joint -->
    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0.0 ${wheel_y_offset} ${wheel_z_offset}" rpy= "${-pi/2} ${pi} ${pi}"/>
        <axis xyz="0 0 -1"/>
    </joint>  



    <!-- base_right_wheel_joint -->
    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0.0 ${-wheel_y_offset} ${wheel_z_offset}" rpy= "${-pi/2} 0.0 0.0"/>
        <axis xyz="0 0 1"/>
    </joint>  



    <!-- caster-Wheel-link -->
    <xacro:macro name="caster_wheel_link" params="prefix">
        <link name="${prefix}_caster_wheel_link">
            <visual>
                <geometry>
                    <mesh filename="${meshes_file_direction}/caster_wheel.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="black"/>
                <origin xyz="0.0 ${caster_wheel_length/2} 0.0" rpy="0.0 0.0 ${-pi/2}"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="black"/>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>               
            </collision>
            <xacro:cylinder_inertia m="0.250" r="${caster_wheel_radius}" h="${caster_wheel_length}"
                                    xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />       
        </link>  
    </xacro:macro>

    <xacro:caster_wheel_link prefix="front"/>
    <xacro:caster_wheel_link prefix="rear"/>


    <!--base_front_caster_wheel_joint-->
    <joint name="base_front_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_caster_wheel_link"/>
        <origin xyz="${base_caster_wheel_link_distance} 0.0 0.00017" rpy= "0.0 0.0 0.0"/>

    </joint>  



    <!--base_rear_caster_wheel_joint-->
    <joint name="base_rear_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_caster_wheel_link"/>
        <origin xyz="${-base_caster_wheel_link_distance} 0.0 0.00017" rpy= "0.0 0.0 0.0"/>
    </joint>

    <!-- odom_link -->
    <!-- <link name="odom" /> -->


    <!-- base_link_odom_joint -->
    <!-- <joint name="odom_joint" type="fixed">
        <parent link="odom"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint> -->


    <!-- base_link_Joint -->
    <!-- <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser"/>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </joint> -->

    <!-- <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
    <ros>
        <robotNamespace>/my_robot</robotNamespace>
        <jointName>base_left_wheel_joint, base_right_wheel_joint</jointName>
        <remapping>joint_states:=/joint_states</remapping>
        <updateRate>100.0</updateRate>
        <alwaysOn>true</alwaysOn>
    </ros>
    </plugin> -->
</robot>
