<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">



    <xacro:property name="wheel_y_offset" value="0.075"/>
    <xacro:property name="wheel_z_offset" value="0.02"/>
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_length" value="0.025"/>
    <xacro:property name="robot_center_to_body_link_x_distance" value="0.054"/>
    <xacro:property name="robot_center_to_body_link_z_distance" value="0.1375"/>
    <xacro:property name="body_length" value="0.1855"/>
    <xacro:property name="body_radius" value="0.07"/>
    <xacro:property name="caster_wheel_radius" value="0.0125"/>
    <xacro:property name="caster_wheel_length" value="0.013"/>
    <xacro:property name="body_caster_wheel_link_distance" value="0.0485"/>
    <xacro:property name="body_link_inertia_z_offset" value="0.0925"/>
    <xacro:property name="lidar_radius" value="0.0278"/>
    <xacro:property name="lidar_length" value="0.0413"/>
    <xacro:property name="gyroscope_length" value="0.015"/>
    <xacro:property name="gyroscope_width" value="0.02"/>
    <xacro:property name="gyroscope_height" value="0.002"/>
    <xacro:property name="body_gyroscope_z_distance" value="${body_length - 0.046}"/>



    <!-- footprint_link -->
    <link name="footprint_link" />



    <!-- body_link -->
    <link name="body_link">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/meshes_description/my_robot.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="grey"/>
            <origin xyz="0.0 0.0 ${robot_center_to_body_link_z_distance}" rpy="${pi/2} 0.0 ${pi/2}"/>          
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${body_radius}" length="${body_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${body_length / 2}" rpy="0.0 0.0 0.0"/>                   
        </collision>
        <xacro:box_inertia m="1000.0" l="${body_length}" w="${body_radius * 2}" h="${body_radius * 2}"
                                xyz="0.0 0.0 ${wheel_z_offset + (body_length / 2) - 0.02}" rpy="0.0 0.0 0.0" />             
    </link>



    <!-- footprint_body_joint -->
    <joint name="footprint_body_joint" type="fixed">
        <parent link="footprint_link"/>
        <child link="body_link"/>
        <origin xyz="0 0 ${caster_wheel_radius}" rpy= "0 0 0"/>
    </joint>        



    <!-- wheel_link -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="orange"/>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>               
            </collision>
            <xacro:cylinder_inertia m="500.0" r="${wheel_radius}" h="${wheel_length}"
                                    xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />     
        </link>  
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>



    <!-- body_left_wheel_joint -->
    <joint name="body_left_wheel_joint" type="continuous">
        <parent link="body_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0.0 ${wheel_y_offset} ${wheel_z_offset}" rpy= "0.0 ${pi/2} ${pi/2}"/>
        <axis xyz="0 0 1"/>
    </joint>  



    <!-- body_right_wheel_joint -->
    <joint name="body_right_wheel_joint" type="continuous">
        <parent link="body_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0.0 ${-wheel_y_offset} ${wheel_z_offset}" rpy= "0.0 ${pi/2} ${pi/2}"/>
        <axis xyz="0 0 1"/>
    </joint>  



    <!-- caster-Wheel-link -->
    <xacro:macro name="caster_wheel_link" params="prefix">
        <link name="${prefix}_caster_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}"/>
                </geometry>
                <material name="black"/>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0  0.0"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="black"/>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>               
            </collision>
            <xacro:cylinder_inertia m="250.0" r="${caster_wheel_radius}" h="${caster_wheel_length}"
                                    xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />       
        </link>  
    </xacro:macro>

    <xacro:caster_wheel_link prefix="front"/>
    <xacro:caster_wheel_link prefix="rear"/>


    <!--body_front_caster_wheel_joint-->
    <joint name="body_front_caster_wheel_joint" type="fixed">
        <parent link="body_link"/>
        <child link="front_caster_wheel_link"/>
        <origin xyz="${body_caster_wheel_link_distance} 0.0 0.00017" rpy= "0.0 ${pi/2} ${pi/2}"/>
    </joint>  



    <!--body_rear_caster_wheel_joint-->
    <joint name="body_rear_caster_wheel_joint" type="fixed">
        <parent link="body_link"/>
        <child link="rear_caster_wheel_link"/>
        <origin xyz="${-body_caster_wheel_link_distance} 0.0 0.00017" rpy="0.0 ${pi/2} ${pi/2}"/>
    </joint>

    <!-- odom_link -->
    <!-- <link name="odom" /> -->


    <!-- body_link_odom_joint -->
    <!-- <joint name="odom_joint" type="fixed">
        <parent link="odom"/>
        <child link="body_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint> -->


    <!-- body_link_Joint
    <joint name="laser_joint" type="fixed">
        <parent link="body_link"/>
        <child link="laser"/>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </joint> -->


</robot>
