# source: https://github.com/ros-drivers/joystick_drivers/tree/ros2/joy
joy_node:
    ros__parameters:
        device_id: 0
        deadzone: 0.3
        autorepeat_rate: 20.0
        sticky_buttons: false

teleop_node:
    ros__parameters:
        axis_linear:                  # Left thumb stick vertical
          x: 1
        scale_linear:
          x: 0.5
        sclae_linear_turbo:
          x: 1.0

        axis_angular:                 # Left thumb stick horizontal
          yaw: 0
        scale_angular:
          yaw: 0.5
        sclae_angular_turbo:
          yaw: 1.0
        
        require_enable_button: true
        enable_button: 4              # Left shoulder button. 
        enable_turbo_button: 5        # Right shoulder button